version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ieca_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ieca_db}
      POSTGRES_USER: ${POSTGRES_USER:-ieca_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ieca_secure_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - ieca_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ieca_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ieca.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ieca_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  ieca_network:
    driver: bridge
